---
dir: 'rtl
---

# تراکنش های مشکوک



## نکاتی که یاد گرفتم:
به دلایل امنیتی PCA روی این داده ها انجام شده است و نیازی به انجام PCA نیست

زمانی که میانگین از میانه بزرگتر باشد ما چولگی به سمت راست داریم و اگر کمتر باید چولگی به سمت چپ داریم.

**مشکل این دیتاست**
یکی از موضوع هایی که باید در این دیتاست کنترل کنیم مشکل Imbalanced بودن کلاسهای ستون هدف است
به طوری که نزدیک به ۳۰۰۰۰۰ تا از تراکنش ها درست و نزدیک به ۵۰۰ تا فقط کلاهبرداری بوده اند.


### نکته بسیار مهم در class imbalanced بودن:
در این پروژه مدل baseline ما accuracy_score هم برای train و هم برای test بسیار بالا بود که به ۹۹ درصد و ۱۰۰ درصد می رسید.
در ظاهر اول مدل بسیار عالی عمل کرده است ولی تنها کاری که مدل کرده این بوده که فقط 0 پیشبینی کرده است چون که ۹۸ درصد داده های ما  (تراکنش سالم بودند)0 بودند
پس در اینجا معیار accuracy_score برای ما قابل اعتماد نیست 

باید از معیاری به نام **Average_precision_score** استفاده کنیم
همان *pr-auc* است.

در اینجا یاد گرفتیم که از pipeline ها در دنیای واقعی استفاده کنیم به دلیل اینکه ما ممکنه که بعدها بخواهیم که یک مدلی رو اضافه یا یک مدلی رو حذف کنیم یا ممکن هست که برای یک نوع مدل scaler بزاریم.


### یک پارامتر مهم در سه مدل استفاده شده در این پروژه:
پارامتر class_weight برای این سه مدل حداقل قابل استفاده است:
- random forest
- decision tree
- hist gradient boosting

زمانی که پارامتر `class_weight` رو برابر 'balanced' قرار بدیم 
داریم نشون می دیم که یکی از کلاسهایی که داریم اقلیت هستند
داریم به مدل می گیم اگر در کلاس اقلیت ها دچار اشکال شدی پنالتی و یا جریمه بیشتری می شوی


فهمیدیم که با توجه به پروژه ای که رو به رو هستیم باید نسبت به یک یا چند معیار اون رو بررسی و یا به اصطلاح fine-tune کنیم 
مثلا برای پروژه های پزشکی می توانیم / باید معیار recall را tune کنیم.

### روش انتخاب مدل و پارامتر
- اول از همه ما بهترین مدل رو پیدا می کنیم از طریق ساختن pipeline
- بعد که بهترین مدل رو پیدا کردیم ما هایپر پارامتر تونینگ می کنیم که بهترین پارامترها رو پیدا می کنیم

*یکی دیگر از نکات این هست وقتی مدل هایی مثل randomforest داریم و پارامترها خیلی طول می کشند تا بهترین حالات آنها انتخاب شود می توانیم (باید) از  RandomSearch استفاده کنیم به جای gridsearch*

میتوانیم threshold های classification رو هم کنترل یا tune کنیم تا مدل رو بهتر کنیم به نظر میاد که overfitting داریم تو این مدل
