---
dir : 'rtl'
---


# Customer Segmentation Clustring Project

کار اصلی در تسک هایی کلاسترینگ که به یک معنایی یادگیری ماشین بدون نظارت قرار می گیرد این هست که بتوان با نداشتن label ها بتوانیم اطلاعاتی راجب دیتایی که داریم به دست بیاوریم. 
کلاسترینگ ها بین گروه های داده رده بندی و طبقه بندی می کند.

- در این پروژه از مدل kmeans استفاده می کنیم و از طریق معیار silhouette_score آن را ارزیابی می کنیم.

برای پیدا کردن بهترین تعداد cluster ها برای مدل نیاز به inertia داریم.
زمانی که نمودار آنها را رسم کردیم باید به دنبال شکست یک دفعه ای باشیم و اون k بهترین تعداد کلاستر ها رو به ما نشون میده
به همین دلیل بهش روش آرنج گفته میشود چون اون عدد که یک دفعه تیز پایین می رود و بعد از آن شیب به صورت تقریبا یکنواخت می شود 

در این داده تعداد کلاستر اپتیمم برابر است با **k = 4**

### سنجش کلاسترها
برای سنجش و ارزیابی تسک های کلاسترینگ نیاز داریم که از معیار silhouette_score استفاده کنیم این معیار میاد و فاصله هر اعضای کلاستر ها رو با خودشون و فاصله هر کلاستر رو با کلاسترهای دیگر مقایسه می کنه و عدد آن بین -۱ تا +۱ قرارد می گیرد.
- +۱ : کلاسترها به صورت خیلی عالی از هم جدا و تشخیص داده شده اند.
- -۱: نشان دهنده این هست که تمام اجزای آن با هم overlap شده اند.
- ۰ : به معنای کمی overlap داشتن هست

**ما در اینجا توانستم به عدد ۰.۴۱ برسیم که برای خودش عددی مناسب است و نشان می دهد که کلاستر ها به خوبی از هم فاصله گرفته اند و هر کلاستر تقریبا به خوبی از هم تشخیص داده شده اند.**