---
dir : 'rtl'
---
# پردازش زبان طبیعی (NLP)

بیشتر تسک های NLP در زمینه یادگیری عمیق قرار می گیرند.

## کارهایی که باید برای NLP انجام بدیم:
- همه حروف رو کوچک می کنیم
- @ ها و لینک ها را پاک می کنیم
- html ها را حذف می کنیم
- می تونه خط اضافی باشه یا به جای یک فاصله، دو تا فاصله داشته باشیم


## نکات در پایتون:
میتوانیم در توابع بیان کنیم که میخواهیم ورودی ما چگونه باشه و خروجی که تابع به ما میده به چه شکل باشه برای انجام اینکار نیاز که در درون تابع یعنی در همون خط اول این رو بیان کنیم.

**def function(s: str) -> str**

این تعریف بیان میکند که ورودی باید text یا string باشد و خروجی هم باید str یا متن باشد برای این تابعی که تعریف کردیم.

در پروژه های NLP می توانیم ستونهای عددی را ایجاد کنیم که هیچ ارتباطی با مدلی که می خواهیم train کنیم ندارد بلکه فقط می خواهیم راجب دیتاستی که داریم بیشتر خبر دار شویم به همین دلیل کارهایی مانند:
- تعداد کاراکترهای که در ستون یک بخش متن داریم
- تعداد کلماتی که در ستون یک بخش از متن داریم
- می توانیم به عنوان مثال داده های متنی را با هم یکی کنیم :
    - به عنوان مثال اگر یک ستون برای عنوان داشتیم و یک ستون برای متن آن عنوان می توانیم آن ها را در یک ستون قرار دهیم


## Data viz. -- مصورسازی داده ها
- با در نظر گرفتن و کشیدن boxplot ها یک نکته ای را متوجه شدیم این هست که:
    - معمولا و تیپیکال اخبار غیر واقعی این هست که متن و از کلماتی بیشتر استفاده میشه


## Vectorization -- وکتورسازی
برای وکتور ساختن دیتافریم میتوانیم مانند قبل از pipeline استفاده کنیم.

در اینجا از TF-IDF استفاده می کنیم برای وکتورسازی دیتافریم خودمون

TF-IDF:

 - TF: Term frequency
 - IDF: Inverse document frequency

**حالا منظور از document چیست؟**


- هر دونه از سطرهای دیتافریم به آن document گفته می شود و به جمع این document ها دیتافریم می گوییم.

به طور کلی مفهومی که داره این هست که آن کلماتی که به تعداد زیاد در یک document وجود دارد و نشان داده می شود به عنوان کلمه مهم نقش می گیرد و کلمه ای که  در همه document ها وجود دارد به این نتیجه ما را می رساند که کلمه مهمی نمی باشد.

هر چه کلمه منحصر به فردی بیشتر در یک document وجود داشته باشد به آن اهمیت بیشتری داده می شود نسبت به دیگر کلمات موجود.

کلماتی که به طور معمول وجود دارد --> مقدار TF-IDF کمی می گیرند

کلماتی که منحصر به فرد و معنادار باشند --> مقدار TF-IDF بیشتری می گیرند.

**بعد از انجام tfidfvectorizor دیگر نیاز به standardScler کردن نیست به دلیل اینکه درون خود اون tfidfvectorizor اینکار انجام شده**


## STOP_WORDS
کلماتی هستند که نیازی به اون ها نیست
در انگلیسی مانند:

- the
- a
- and
- is


## ngram_range
یعنی اینکه چطوری به کلماتی که وجود داره و کنار هم قرار گرفته می توانیم معنا بدیم برای شما دو مثال می زنیم:

- اگر ngram = (1,1) باشد:
به عنوان مثال کلمه  Machine Learning به این صورت تبدیل می شود
Machine , Learning 

- اگر ngram = (1,2) باشد:
کلمه Machine Learning به این صورت قرار می گیرد:
Machine, Machine Learning

