---
dir: 'rtl'
---

# پروژه رگرسیون قیمت خانه 

ستون های categorical و numerical رو باید جدا بررسی از هم دیگه بررسی کنیم.

## نکات این دیتاست
- ما ۲۰۷ تا داده های از دست رفته در ستون total_bedrooms داریم.
    برای تشخیص داده های از دست رفته ای که با یک placeholder جایگذاری شده اند، باید بگردیم تا پر تکرار ترین دادها را برای هر ستون پیدا کنیم تا متوجه placeholder ها بشویم.
- در این دیتاست ما دیتا تارگت ما cap شده به این معنا که ماکزیمم مقداری که قیمت ما میگیره 500k هست و این هم محدودیتی برای مدل ما حساب میشه و مدل ما به خوبی دیتای ما می باشد.





ما کارهای preprocessing رو بعد از train_test_split انجام میدیم تا از مشکل data leakage جلوگیری کنیم.

- نکته استفاده از مدل baseline داشتن این هست که نشان دهیم که چقدر مدل ما توانسته پیشرفت کنه.


- ارزیابی مدل baseline ما:
    - برای train: 0.65
    - برای test: 0.62

برای معیارهای دیگر باید بررسی کنیم که ستون هدف ما در چه مقیاسی قرار دارد به همین جهت آنهارا با هم مقایسه می کنیم.
**مثلا اگر ستون هدف ما در معیار میلیون دلار باشد ۷۰k برای ما مقدار بدی برای مدل  نیست.**


- به طور کلی رگرسیون LASSO  نیازمند تعداد تکرار بیشتری است تا به همگرایی برسد
- در اینجا مدل HistBoostingGradientRegressor بهترین مدل ما بود.




یکی از نکات مهم این هست که ما در classification از accuracy استفاده می کنیم و هرچی بالاتر باشه مدل ما بهتر کار میکنه ولی در شرایط رگرسیون ما با ارور سرو کار داریم و این نشون میده که هر چی این ارور کوچکتر باشه مدل بهتره به همین دلیل از علامت منفی استفاده می کنیم.
به همین دلیل در gridsearch یا هر search دیگه ای ما از منفی اون معیار استفاده می کنیم یعنی اینکه هر چی بیشتر باشه و منفی کنیم اون رو کمتر میشه
داریم به sklearn می گیم که مدل ما رو برای ارور پایین تر بهینه کنه تا بالاتر
