# بررسی هزینه بیمه 

- در کتابخانه هایی که فراخوانی کردیم kfold برای این استفاده میشه که داده ها رو به تعداد مشخص بخش ها تبدیل کنیم و با استفاده از cross_validation اونها رو بیاییم بررسی کنیم یعنی اینکه اگه kfold = 5 باشد، یکی از اون ها test و چهارتای دیگر train می شود.

- یکی دیگر از چیزهایی جدید استفاده از transformedtargetcolumn هست. که به دلیلی داده ای که داریم از آن استفاده می کنیم.
    - دلیل استفاده این هست به دلیلی چولگی به سمت راست ستون هدف (تارگت ما) نیاز داریم که یک log transform انجام بدیم تا داده ما آماده برای رگرسیون شوند.
    - داریم کاری می کنیم که فرضیات پایه ای رگرسیون رد نشوند

- **یک نکته آماری** : زمانی که میانگین بیشتر از میانه می شود می دانیم که ما یک *چولگی به سمت راست* داریم 

- داده های عددی ما به ترتیب به این صورت هستند:
    - age: تقریبا به صورت یک توزیع یکنواخت می باشند
    - bmi: دارای توزیع نرمال می باشد
    - charges: چولگی به سمت راست دارد


**بین ستون ها هیچ همخطی وجود ندارد**

برای داده های خطی و یا regularization ها نیازمند feature scaling مانند standardanization هستیم
 
 برای روابطی که خطی نیستند و با مدل هایی مثل رگرسیون خطی قابل توضیح دادن نمی باشند ، می توانیم از مدل های درختی استفاده کنیم

 - بهترین مدل قابل استفاده برای این دیتاست:
    - مدل randomforest هست که از بقیه مدل ها بهتر عمل کرد.
    