---
dir: rtl
---
# بررسی 

## توضیح راجب دیتاست
این دیتاست یک مشکل classification دارد که هر سطر آن نشان دهنده یک مشاهده است که در ستون آخر آن ما با لیبل یا Target داریم که دو وضعیت M یعنی Mines یا نشان دهنده مین هست 
یا R که نشان دهنده وجود سنگ می باشد.



### چیزایی که یاد گرفتم:

- **در پایتون:**
    - وقتی دیتاستی داریم که هیچ سطر و ستونی براش تعریف نشده می تونیم در pandas زمانی که داریم از pd.read_csv() استفاده میکنیم درون پرانتز از پارامتر header = None استفاده کنیم. از همین روش دیگر سطر اول را به عنوان نام ستون ها نمی گیرد بلکه از اعداد طبیعی برای نامگذاری استفاده می کند.
    - یاد گرفتم که اگه نموداری های زیادی نیاز هست رسم کنیم می تونیم از subplots استفاده کنیم.
    با استفاده از این ابزار می تونیم همه نمودارها رو در یک شکل قرار بدیم.


- **در یادگیری ماشین:**
    - زمانی که دیتاست با سطرهای کمی داریم به طور کلی نمی شود از مدلهای پیچیده مانند RandomForest یا XGboost استفاده کرد و مدل هایی مانند LogisticRegression ، SVM می توانند به خوبی کار کنند
    - گاهی اوقات به جای اینکه خالی بزارند جای داده های گمشده رو اونها رو با اعداد خیلی بزرگ یا خیلی کوچیک پر میکنند تا مشکلی در کد ایجاد نشه به همین دلیل ما نیاز داریم که اول این مشکل رو پیدا کنیم و کارهایی که نیاز هست رو روی این نوع داده ها انجام بدیم.
    - در زمانی که می خوایم داده های پرت رو کنترل کنیم اولین کاری که نیاز هست انجام بدیم این هست که داده هایی که داریم رو بشناسیم.
    **مهمترین نکته این هست که به صورت پیش فرض فقط جایگزین نکنیم (با میانگین یا میانه) داده های پرت رو**
    اگر در یک range بودن داده های پرت ما نیاز نیست که نگران باشیم



## اطلاعاتی که از مرحله EDA گرفتیم.
- این دیتاست دارای سطر (داده های کمی) است فقط ۲۰۸ داده داریم، میتوان از مدل های ساده استفاده کنیم
- این دیتاست دارای ستون های عددی است بدون ستون های categorical
- ستون y به خوبی بالانس شده است
- می توانیم ببنیم که دو کلاس M و R میانگین آنها با هم متفاوت است میتوانیم آزمون هم انجام دهیم.
- بیشتر داده ها جولگی به سمت راست دارند
- داده های پرت داریم ولی در range قرار دارند.
- همبستگی بین بعضی از داده ها وجود دارند می توانیم بعضی از آنها را حذف کنیم.


یکی از چیزهای مهمی که یاد گرفتم این بود که بالاخره جواب اینکه با این مدلی که داریم چیکار کنیم رو متوجه شدم این هست که باید از اون scaler استفاده کنیم و فقط transform کنیم نه fit 
بعد از اون طبق مدلی که برازش کردیم همه رو میزاریم توی یک تابع و از کاربر اطلاعات می گیریم تا اون چیزی  که نیاز هست رو پیشبینی کنیم.


